"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { db } from "@/lib/firebase/firebase";
import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import toast from "react-hot-toast";
import { Panel } from "@/features/admin/ui/Panel";
import { Field, fieldClass, textareaClass } from "@/features/admin/ui/Field";
import { AdminButton } from "@/features/admin/ui/AdminButton";
import { useLocale } from "@/components/providers/LocaleProvider";

function CreateOfferForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { t } = useLocale();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    title: "",
    projectName: "",
    details: "",
    price: "",
    developerName: searchParams.get("devName") || "",
    developerEmail: searchParams.get("devEmail") || "",
    developerPhone: searchParams.get("devPhone") || "",
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const docRef = await addDoc(collection(db, "offers"), {
        ...formData,
        status: "pending",
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });

      toast.success(t("admin.offers.successMessage") || "Offer created successfully! OTP will be generated by Cloud Function.");
      router.push("/admin/dashboard");
    } catch (error: any) {
      toast.error(t("admin.offers.errorMessage") || "Failed to create offer");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col gap-6 pt-4 sm:pt-6 pb-20">
      <Panel title={t("admin.offers.create") || "Create Technical / Financial Offer"}>
        <form onSubmit={handleSubmit} className="flex flex-col gap-8 p-6 sm:p-8">
          <div className="grid gap-6 md:grid-cols-2">
            <Field label={t("admin.offers.offerTitle") || "Offer Title"}>
              <input
                type="text"
                name="title"
                required
                value={formData.title}
                onChange={handleChange}
                placeholder={t("admin.offers.offerTitlePlaceholder") || "e.g. Phase 1 Development"}
                className={fieldClass}
              />
            </Field>

            <Field label={t("admin.offers.projectName") || "Project Name"}>
              <input
                type="text"
                name="projectName"
                required
                value={formData.projectName}
                onChange={handleChange}
                placeholder={t("admin.offers.projectNamePlaceholder") || "e.g. Al-Riyadh Compound"}
                className={fieldClass}
              />
            </Field>
          </div>

          <Field label={t("admin.offers.technicalDetails") || "Technical Details"}>
            <textarea
              name="details"
              required
              value={formData.details}
              onChange={handleChange}
              rows={4}
              placeholder={t("admin.offers.technicalDetailsPlaceholder") || "Describe the scope of work..."}
              className={textareaClass}
            />
          </Field>

          <div className="grid gap-6 md:grid-cols-3">
            <Field label={t("admin.offers.financialAmount") || "Financial Amount (SAR)"}>
              <input
                type="number"
                name="price"
                required
                value={formData.price}
                onChange={handleChange}
                placeholder={t("admin.offers.financialAmountPlaceholder") || "e.g. 50000"}
                className={fieldClass}
              />
            </Field>

            <Field label={t("admin.offers.developerEmail") || "Developer Email"}>
              <input
                type="email"
                name="developerEmail"
                required
                value={formData.developerEmail}
                onChange={handleChange}
                placeholder={t("admin.offers.developerEmailPlaceholder") || "dev@example.com"}
                className={fieldClass}
              />
            </Field>

            <Field label={t("admin.offers.developerPhone") || "Developer Phone"}>
              <input
                type="tel"
                name="developerPhone"
                required
                value={formData.developerPhone}
                onChange={handleChange}
                placeholder={t("admin.offers.developerPhonePlaceholder") || "+966 50..."}
                className={fieldClass}
              />
            </Field>
          </div>

          <Field label={t("admin.offers.developerName") || "Developer Name"}>
            <input
              type="text"
              name="developerName"
              required
              value={formData.developerName}
              onChange={handleChange}
              placeholder={t("admin.offers.developerNamePlaceholder") || "e.g. Ahmed Ali"}
              className={fieldClass}
            />
          </Field>

          <div className="flex flex-wrap items-center justify-end gap-3 pt-4 sm:pt-6">
            <AdminButton
              type="button"
              tone="danger"
              onClick={() => router.back()}
              disabled={loading}
              className="bg-transparent text-[#6B7280] hover:bg-black/5 hover:text-[#0a0f1d]"
            >
              {t("admin.offers.cancel") || "Cancel"}
            </AdminButton>
            <AdminButton type="submit" disabled={loading}>
              {loading ? (t("admin.offers.submitting") || "Creating...") : (t("admin.offers.submit") || "Create & Send Offer")}
            </AdminButton>
          </div>
        </form>
      </Panel>
    </div>
  );
}

import { Suspense } from "react";
export default function CreateOfferPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <CreateOfferForm />
    </Suspense>
  );
}
